author: Prashant SG

md-to-html:
  src-dir: md
  gen-dir: md/html
  template-techbit-html: template-techbit-.html
  placeholder:
    id: placeholder-md-
    file: script/gen/placeholder.js
    script: |
      $(function () {{
        $("#placeholder-md-{}").load("{}");
      }});

plantuml:
  commands:
    - "java -jar ~/Downloads/plantuml.jar plantuml/uml-relations/*.plantuml"
    - "mkdir img/uml-relations"
    - "mv plantuml/uml-relations/*.png img/uml-relations/."
